"""DB UPLOAD

Revision ID: 418b795723fc
Revises: 
Create Date: 2026-02-07 23:32:16.840614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '418b795723fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('payment_method_mock', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('must_haves', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('checkout_status', sa.String(length=50), nullable=True),
    sa.Column('pdf_receipt_url', sa.String(length=255), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('estimated_delivery_global', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spec_id'], ['shopping_specs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('retailer_name', sa.String(length=50), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('delivery_estimate', sa.String(length=100), nullable=True),
    sa.Column('rank_score', sa.Integer(), nullable=True),
    sa.Column('rank_explanation', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['spec_id'], ['shopping_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('retailer', sa.String(length=50), nullable=False),
    sa.Column('retailer_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('product_candidates')
    op.drop_table('orders')
    op.drop_table('shopping_specs')
    op.drop_table('chat_messages')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
